name: galactic-spin 
dependencies:
  - python>=3.6
  - anaconda
  - numpy
  - scipy
  - emcee
  - pandas
  - astropy::gammapy
  - astropy::corner
  - matplotlib
  - mpld3
  - tabulate
  - h5py
  - lmfit
  - ipykernel
  - nb_conda_kernels
  - anaconda::pytest
  - pip
  - pip:
    - svgpathtools
    - bootstrapped 
    - papermill
